Repository Wolkenfarmer/Space-Invader, pull requests merged in 2020-12, with the labels that each got.

#3 Add multiple dummy sprites
  Assets/Sprites.meta
  Assets/Sprites/bullet.png
  Assets/Sprites/defaultenemy.png
  Assets/Sprites/emp.png
  Assets/Sprites/player.png
  Assets/Sprites/specialenemy.png
Labels: PR: Ready for Review

#1 Add base classes, player and debug movement via keyboard
  .vsconfig
  Assets/Prefabs.meta
  Assets/Prefabs/Bullets.meta
  Assets/Prefabs/Bullets/LaserBullet.prefab
  Assets/Prefabs/Bullets/LaserBullet.prefab.meta
  Assets/Scenes/game.unity
  Assets/Scenes/game.unity.meta
  Assets/Scripts.meta
  Assets/Scripts/Bullets.meta
  Assets/Scripts/Bullets/BulletBehaviorScript.cs
  Assets/Scripts/Bullets/BulletBehaviorScript.cs.meta
  Assets/Scripts/Bullets/LaserBulletBehaviorScript.cs
  Assets/Scripts/Bullets/LaserBulletBehaviorScript.cs.meta
  Assets/Scripts/OutOfScreenKillBehaviorScript.cs
  Assets/Scripts/OutOfScreenKillBehaviorScript.cs.meta
  Assets/Scripts/ScreenClampBehaviorScript.cs
  Assets/Scripts/ScreenClampBehaviorScript.cs.meta
  Assets/Scripts/Spaceships.meta
  Assets/Scripts/Spaceships/PlayerBehaviorScript.cs
  Assets/Scripts/Spaceships/PlayerBehaviorScript.cs.meta
  Assets/Scripts/Spaceships/SpaceShipBehaviorScript.cs
  Assets/Scripts/Spaceships/SpaceShipBehaviorScript.cs.meta
Labels: PR: Is Dependency, PR: Ready for Review

#10 Restrict player movement and allow specific out-of-bounds enemy movement
  Assets/Prefabs/Enemies/DefaultEnemy.prefab
  Assets/Scenes/game.unity
  Assets/Scripts/BlockadeBehaviorScript.cs
  Assets/Scripts/BlockadeBehaviorScript.cs.meta
  Assets/Scripts/GameBehaviorScript.cs
  Assets/Scripts/ScreenClampBehaviorScript.cs
  Assets/Sprites/blockade_colors.png
  Assets/Sprites/blockade_colors.png.meta
Labels: PR: Ready for Review, enhancement

#11 Added wave and unit logic
  Assets/Prefabs/Enemies/DefaultEnemy.prefab
  Assets/Scenes/game.unity
  Assets/Scripts/GameBehaviorScript.cs
  Assets/Scripts/Spaceships/DefaultEnemyBehaviorScript.cs
  Assets/Scripts/Spaceships/PlayerBehaviorScript.cs
  Assets/Scripts/Spaceships/Unit.cs
  Assets/Scripts/Spaceships/Unit.cs.meta
  Assets/Scripts/WaveScript.cs
  Assets/Scripts/WaveScript.cs.meta
Labels: PR: Ready for Review

#12 Rename scripts
  Assets/Scripts/Blockade.cs
  Assets/Scripts/Blockade.cs.meta
  Assets/Scripts/Bullets/Bullet.cs
  Assets/Scripts/Bullets/Bullet.cs.meta
  Assets/Scripts/Bullets/LaserBullet.cs
  Assets/Scripts/Bullets/LaserBullet.cs.meta
  Assets/Scripts/Bullets/LaserBulletBehaviorScript.cs
  Assets/Scripts/GameController.cs
  Assets/Scripts/GameController.cs.meta
  Assets/Scripts/IDamageableObject.cs
  Assets/Scripts/ScreenClamper.cs
  Assets/Scripts/ScreenClamper.cs.meta
  Assets/Scripts/ScreenboundsKiller.cs
  Assets/Scripts/ScreenboundsKiller.cs.meta
  Assets/Scripts/Spaceships/Enemyship.cs
  Assets/Scripts/Spaceships/Enemyship.cs.meta
  Assets/Scripts/Spaceships/Playership.cs
  Assets/Scripts/Spaceships/Playership.cs.meta
  Assets/Scripts/Spaceships/Spaceship.cs
  Assets/Scripts/Spaceships/Spaceship.cs.meta
  Assets/Scripts/Spaceships/WaveUnit.cs
  Assets/Scripts/Spaceships/WaveUnit.cs.meta
  Assets/Scripts/WaveController.cs
  Assets/Scripts/WaveController.cs.meta
Labels: PR: Is Dependency, PR: Ready for Review

#13 Add Level logic and game restart
  Assets/Scenes/game.unity
  Assets/Scripts/GameController.cs
  Assets/Scripts/GameState.cs
  Assets/Scripts/GameState.cs.meta
  Assets/Scripts/Spaceships/Playership.cs
  Assets/Scripts/UIController.cs
  Assets/Scripts/UIController.cs.meta
  Assets/Scripts/WaveController.cs
  Assets/Sprites/Colors.meta
  Assets/Sprites/Colors/blockade_colors.png
  Assets/Sprites/Colors/blockade_colors.png.meta
  Assets/Sprites/Colors/text_background_color.png
  Assets/Sprites/Colors/text_background_color.png.meta
Labels: PR: Has Dependency, PR: Ready for Review

#15 Add Mainmenu including four buttons
  .gitignore
  Assets/Scenes/menu.unity
  Assets/Scenes/menu.unity.meta
  Assets/Scripts/GameController.cs
  Assets/Scripts/GameState.cs
  Assets/Scripts/Menu.meta
  Assets/Scripts/Menu/EndlessButton.cs
  Assets/Scripts/Menu/EndlessButton.cs.meta
  Assets/Scripts/Menu/ExitButton.cs
  Assets/Scripts/Menu/ExitButton.cs.meta
  Assets/Scripts/Menu/MenuController.cs
  Assets/Scripts/Menu/MenuController.cs.meta
  Assets/Scripts/Menu/SettingsButton.cs
  Assets/Scripts/Menu/SettingsButton.cs.meta
  Assets/Scripts/Menu/StoryButton.cs
  Assets/Scripts/Menu/StoryButton.cs.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/SceneTemplateSettings.json
  UserSettings/EditorUserSettings.asset
Labels: PR: Ready for Review
